# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('contents', models.TextField(verbose_name='\u5185\u5bb9')),
                ('times', models.IntegerField(default=0, editable=False, verbose_name='\u9605\u8bfb\u91cf')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4e00\u6b21\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7c7b\u540d')),
            ],
            options={
                'verbose_name': '\u7c7b\u540d',
                'verbose_name_plural': '\u7c7b\u540d',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog_main.Category'),
        ),
    ]
